import assert from "node:assert/strict";
import { HighScoreTracker, difficultyHighScores } from "../public/web/high-score.js";
assert.deepEqual(difficultyHighScores({highScores: {hard: 500}, entries: [{difficulty: "normal", score: 1000}]}), {easy: 0, normal: 1000, hard: 500});
const tracker = new HighScoreTracker();
const select = {screen: "select", status: "select", difficulty: "normal", score: 0};
const run = score => ({screen: "game", status: "playing", difficulty: "normal", score});
assert.equal(tracker.update(select, run(200)), false, "unknown offline record must not celebrate");
tracker.load({highScores: {normal: 1000}});
assert.equal(tracker.update(select, run(1000)), false, "ties do not celebrate");
assert.equal(tracker.update(run(1000), run(1100)), true);
assert.equal(tracker.update(run(1100), run(1200)), false, "sound only once per run");
tracker.load({highScores: {normal: 1000}});
assert.equal(tracker.label("normal"), "NORMAL HIGH 0001200", "refresh cannot erase the current record");
assert.equal(tracker.update({...run(1200), status: "game_over"}, run(100)), false);
assert.equal(tracker.newHigh, false, "retry clears the marker");
assert.equal(tracker.update(run(100), run(1300)), true);
assert.equal(tracker.update(run(1300), select), false);
assert.equal(tracker.newHigh, false);
assert.equal(tracker.label("hard"), "HARD HIGH 0000000");
console.log("Difficulty high-score checks passed");
